一番最初に誰が始めた物語なのか明示する必要があります。
takeokunn/awesome-yasunori pull request #1
Opened 2024-09-18 09:59 UTC by yasunori0418

お前が始めた物語だろ!!!

2024-09-18 10:02 UTC, takeokunn commented
yasunori(原義)からのコメントと明記してください

2024-09-18 10:03 UTC, yasunori0418 commented
`(原義)`は必要ですか?

2024-09-18 10:04 UTC, takeokunn commented
原義だという認識であれば原義が必要でしょうし、そうでなければ不要でしょう

2024-09-18 10:06 UTC, gamoutatsumi commented
お前**で**始めた物語では 🤔

2024-09-18 10:15 UTC, yasunori0418 commented
fixed

2024-09-18 10:17 UTC, natsukium requested changes

2024-09-18 10:17 UTC, natsukium commented on README.md
> +> お前([takeokunn](https://github.com/takeokunn))で始めた物語だろ！！
```suggestion
> お前([yasunori](https://github.com/yasunori0418))で始めた物語だろ！！
```

2024-09-18 10:21 UTC, yasunori0418 commented on README.md
> +> お前([takeokunn](https://github.com/takeokunn))で始めた物語だろ！！
いえ、これはたけてぃが始めが物語です。
私は始めていないですね

2024-09-21 03:17 UTC, takeokunn commented on README.md
> +> お前([takeokunn](https://github.com/takeokunn))で始めた物語だろ！！
「お前([takeokunn](https://github.com/takeokunn)) が俺([yasunori](https://github.com/yasunori0418))で始めた物語」という記述に変更してください

2024-09-21 03:39 UTC, yasunori0418 commented on README.md
> +> お前([takeokunn](https://github.com/takeokunn))で始めた物語だろ！！
これは良い提案ですね。
この提案に沿って、修正しました

2024-09-21 03:45 UTC, takeokunn commented
LGTM!!

2024-09-21 03:45 UTC, merged