flakeファイルの追加
takeokunn/awesome-yasunori pull request #8
Opened 2024-09-29 12:30 UTC by Comamoca

flakeファイルを追加しました。
`nix fmt`でNixとTOMLのフォーマットが走ります。

また、`nix build`でビルドが実行されますが成果物等は出力しません。
これは後にREADMEファイルを生成することを見越しての措置です。

2024-09-29 12:31 UTC, tomoya commented
こういうのは CI とセットのプルリクを作成するのがベストですね。

2024-09-29 14:57 UTC, satler-git commented
#6 で分割されているTomlがこっちにもあるので削除できますか?

2024-09-29 17:01 UTC, akirak requested changes

2024-09-29 17:01 UTC, akirak commented on flake.nix
> +          yasunori = stdenv.mkDerivation {
[pkgs.emptyFile](https://github.com/NixOS/nixpkgs/blob/7cba8410f766cfea58603091ad2793cae58d3104/pkgs/build-support/trivial-builders/default.nix#L886)が使えます。

`pkgs/build-support/trivial-builders/default.nix`には、この他にも便利な関数が定義されているので、見ておくといいです。

2024-09-29 17:03 UTC, akirak commented
すみません。部外者ですがレビューしました。（twitterで鍵垢のtakeokunnの相互フォロワーです）

2024-09-29 21:42 UTC, Comamoca commented on flake.nix
> +    nixpkgs.url = "github:nixos/nixpkgs?ref=nixos-unstable";
`nixos-*`がLinuxでしかビルドされていないのもflakeではnixpkgsがデフォルトで設定されているのも初めて知りました。
ありがとうございます！

2024-09-29 21:46 UTC, Comamoca commented on flake.nix
> +          yasunori = stdenv.mkDerivation {
今まで空のDerivationを作る良い方法を知らず悩んでいたところもあるのでありがたいです。
`pkgs/build-support/trivial-builders/default.nix`も読んでみます。

2024-09-29 21:48 UTC, Comamoca commented
以下の変更を行いました。

- Nix以外のformatterを削除
- nixpkgsのURLを`nixpkgs-unstable`に変更
- 空のresultを作成するだけのmkDerivationをemptyDirectoryに変更

CIについてはREADMEを生成するプログラムを別の方が作っていると思うので、それ次第だと思っています。
一応自分の方でCIの準備をしておきます。

2024-09-30 07:43 UTC, takeokunn commented
@akirak
こんな ~どうしようもない~ repoにレビューありがとうございます!!

2024-10-01 00:33 UTC, takeokunn commented
@Comamoca 
以下の対応をしました。

- conflictの解消
- flake.nixの対応
- `nix flake check` のCI追加

#10 との繋ぎ込みもしたいので一旦mergeしちゃいます!! ありがとうございました!!

2024-10-01 00:33 UTC, merged